### ISSUE TITLE
Add requirements.txt

### ISSUE THREAD

**Issue by andybak** [allytrope/shapeshift#2]
```
numpy~=1.22.3
PySide6~=6.2.3
moderngl~=5.6.4
pyrr~=0.10.3
sympy~=1.10
```

Also "import OpenGL.GL as GL" can be removed from polyhedra.py

**Comment by allytrope** [comment]
Thanks! Good idea. That will make it easier to replicate the environment. I just created the `requirements.txt` file and removed that unnecessary line.
